language: cpp

os: osx

osx_image: xcode10.3

addons:
  homebrew:
    brewfile: true

script:
  - mkdir build
  - cd build
  - cmake ..
  - make package -j$(sysctl -n hw.physicalcpu)

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "build/devilutionx.dmg"
  skip_cleanup: true
  on:
    tags: true
